CREATE TABLE tb_clube(
    id INTEGER GENERATED BY DEFAULT AS IDENTITY,
    nome VARCHAR(30) NOT NULL,
    abreviacao VARCHAR(3) NOT NULL,
    escudo_url VARCHAR(255) NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE tb_atleta(
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    nome VARCHAR(30) NOT NULL,
    apelido VARCHAR(15),
    foto_url VARCHAR(255) NOT NULL,
    posicao VARCHAR(20) NOT NULL,
    clube_id INTEGER NOT NULL,
    PRIMARY KEY (id),
    FOREIGN KEY (clube_id) REFERENCES tb_clube (id)
);

