-- Adiciona os campos de identificação e performance
ALTER TABLE tb_atleta ADD COLUMN external_id INTEGER UNIQUE;
ALTER TABLE tb_atleta ADD COLUMN preco NUMERIC(4,2);
ALTER TABLE tb_atleta ADD COLUMN media NUMERIC(4,2);
ALTER TABLE tb_atleta ADD COLUMN jogos_num INTEGER;
ALTER TABLE tb_atleta ADD COLUMN status VARCHAR(20);

-- Adiciona os 18 campos do Scout (@Embedded mapeia direto para a tabela pai)
ALTER TABLE tb_atleta ADD COLUMN ds INTEGER DEFAULT 0;
ALTER TABLE tb_atleta ADD COLUMN g INTEGER DEFAULT 0;
ALTER TABLE tb_atleta ADD COLUMN a INTEGER DEFAULT 0;
ALTER TABLE tb_atleta ADD COLUMN sg INTEGER DEFAULT 0;
ALTER TABLE tb_atleta ADD COLUMN fs INTEGER DEFAULT 0;
ALTER TABLE tb_atleta ADD COLUMN ff INTEGER DEFAULT 0;
ALTER TABLE tb_atleta ADD COLUMN fd INTEGER DEFAULT 0;
ALTER TABLE tb_atleta ADD COLUMN ft INTEGER DEFAULT 0;
ALTER TABLE tb_atleta ADD COLUMN ps INTEGER DEFAULT 0;
ALTER TABLE tb_atleta ADD COLUMN de INTEGER DEFAULT 0;
ALTER TABLE tb_atleta ADD COLUMN dp INTEGER DEFAULT 0;
ALTER TABLE tb_atleta ADD COLUMN gc INTEGER DEFAULT 0;
ALTER TABLE tb_atleta ADD COLUMN cv INTEGER DEFAULT 0;
ALTER TABLE tb_atleta ADD COLUMN ca INTEGER DEFAULT 0;
ALTER TABLE tb_atleta ADD COLUMN gs INTEGER DEFAULT 0;
ALTER TABLE tb_atleta ADD COLUMN pp INTEGER DEFAULT 0;
ALTER TABLE tb_atleta ADD COLUMN pc INTEGER DEFAULT 0;
ALTER TABLE tb_atleta ADD COLUMN fc INTEGER DEFAULT 0;
